---
rook_ceph_vars:
  kubernetes:
    helm:
      chart:
        version: "{{ versions.rook_ceph }}"
        operator:
          name: rook-ceph
        cluster:
          name: rook-ceph-cluster
      repository:
        name: rook-release
        url: https://charts.rook.io/release
        github: https://github.com/rook/rook
    namespace: rook-ceph
    dashboard:
      enabled: true
    ingress:
      enabled: true
      subdomain: ceph
    monitoring:
      enabled: true
    toolbox:
      enabled: true
    object_storage:
      storageClass: ceph-bucket
      region: us-east-1
      ingress:
        enabled: true
        subdomain: ceph-os
      metadataPool:
        size: 1
    cephCluster:
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
        allowMultiplePerNode: true
      blockPool:
        size: 1
      fileSystem:
        metadataPool:
          size: 1
        dataPool:
          size: 1
