replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}
  
secretFrom: {}
  # name: the name of the secret to mount

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

httproute:
  enabled: false
  annotations: {}
  gatewayName: kong
  gatewayNamespace: kong-system
  hostnames: []
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      # backendRefs can be omitted to use the default service
      # backendRefs:
      #   - name: custom-service
      #     kind: Service
      #     port: 8080
    # Example of a more complex rule
    # - matches:
    #   - headers:
    #       - name: "X-Version"
    #         value: "v3"
    #     path:
    #       type: PathPrefix
    #       value: /test
    #   backendRefs:
    #     - name: api-v2
    #       kind: Service
    #       port: 8081
    
  # Additional HTTPRoutes
  additionalRoutes: []

resources: {}

livenessProbe:
  httpGet:
    path: /probe
    port: http
readinessProbe:
  httpGet:
    path: /probe
    port: http

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

externalSecret:
  enabled: false
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: default-secret-store
  target:
    template:
      data: {}
  data: []

objectBucketClaims:
  enabled: false
  buckets:
    - name: example-bucket

hooks:
  migration:
    enabled: false
