---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - k3s
    - prometheus

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ redis_vars.kubernetes.helm.repository.name }}"
        repo_url: "{{ redis_vars.kubernetes.helm.repository.url }}"

    - name: Create Redis Grafana dashboard ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
        definition: 
          apiVersion: v1
          kind: ConfigMap  
          metadata:
            name: redis-grafana-dashboard
            namespace: "{{ prometheus_vars.kubernetes.namespace }}"
            labels:
              grafana_dashboard: "1"
          data:
            redis-dashboard.json: "{{ lookup('file', 'defaults/redis_dashboard.json') | from_json | to_nice_json }}"