---
helm_vars:
  directory:
    share: /usr/local/share/helm
  environment:
    HELM_NAMESPACE: default
  plugins:
    - name: diff
      enabled: true
      packages:
        - python3-jsonpatch
      repository:
        url: https://github.com/databus23/helm-diff
      version: v3.9.9
  release:
    distro: debian
    key: helm-archive-keyring.gpg
    repository:
      channel: stable
      key: signing.asc
      url: https://baltocdn.com/helm