apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  namespace: document-chat
  name: postgres-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  postgresVersion: "16"
  postgresql.conf:
    shared_buffers: '512MB'
    random_page_cost: '1.5'
    password_encryption: 'scram-sha-256'
    log_checkpoints: 'on'