apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  namespace: document-chat
  name: postgres-cluster-scripts
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  scripts:
  - name: create-user
    scriptFrom:
      secretKeyRef:
        name: chat-database-user-sql
        key: create-user-sql
  - name: create-database
    scriptFrom:
      secretKeyRef:
        name: chat-database-user-sql
        key: create-chat-database-sql
  - name: create-theme-database
    scriptFrom:
      secretKeyRef:
        name: chat-database-user-sql
        key: create-theme-database-sql
  - name: create-scope-management-database
    scriptFrom:
      secretKeyRef:
        name: chat-database-user-sql
        key: create-scope-management-database-sql
  - name: create-app-repository-database
    scriptFrom:
      secretKeyRef:
        name: chat-database-user-sql
        key: create-app-repository-database-sql
  - name: create-ingestion-database
    scriptFrom:
      secretKeyRef:
        name: chat-database-user-sql
        key: create-ingestion-database-sql
