apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  namespace: document-chat
  name: postgres-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  postgres:
    version: "16.4"
    extensions:
      - name: pg_trgm
      - name: pg_stat_statements
  instances: 3
  sgInstanceProfile: "postgres-instance-profile"
  pods:
    disableConnectionPooling: true
    persistentVolume:
      size: "10Gi"
      storageClass: ceph-block
  configurations:
    sgPostgresConfig: "postgres-config"
    backups:
      - sgObjectStorage: "postgres-backup-config"
        cronSchedule: "0 * * * *"
        retention: 6
  managedSql:
    scripts:
      - sgScript: postgres-cluster-scripts
  distributedLogs:
    sgDistributedLogs: "postgres-distributed-logs"
  prometheusAutobind: true
