---
nvidia_gpu_operator_vars:
  kubernetes:
    default_settings:
      operator:
        defaultRuntime: containerd
      toolkit:
        enabled: true
    helm:
      chart:
        name: gpu-operator
        version: "{{ versions.nvidia_gpu_operator }}"
      repository:
        org: nvidia
        url: https://helm.ngc.nvidia.com/nvidia
    namespace: gpu-operator
