---
litellm_vars:
  kubernetes:
    namespace: litellm
    helm:
      chart:
        name: litellm
        version: "{{ versions.litellm }}"
      repository:
        org: berriai
        url: harbor.konsti.org/library
    ingress:
      subdomain: litellm
  postgres_cluster:
    name: litellm-db-cluster
    user: litellm
    database: litellm
