---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - basic_auth
    - certmanager
    - k3s
    - redis
- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ harbor_vars.kubernetes.helm.repository.org }}"
        repo_url: "{{ harbor_vars.kubernetes.helm.repository.url }}"

    - name: Create harbor resources
      run_once: true
      block:
        - name: Create harbor namespace
          kubernetes.core.k8s:
            name: "{{ harbor_vars.kubernetes.namespace }}"
            api_version: v1
            kind: Namespace
            state: present
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"

        - name: Create harbor database
          kubernetes.core.k8s:
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            definition: "{{ lookup('ansible.builtin.template', 'harbor_database.j2') }}"
            namespace: "{{ harbor_vars.kubernetes.namespace }}"

        - name: Create harbor Redis instance
          kubernetes.core.helm:
            chart_ref: "{{ redis_project_chart }}"
            chart_version: "{{ redis_vars.kubernetes.helm.chart.version }}"
            create_namespace: false
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            name: "harbor-redis"
            namespace: "{{ harbor_vars.kubernetes.namespace }}"
            update_repo_cache: true
            values: "{{ lookup('ansible.builtin.template', 'harbor_redis.j2') | from_yaml }}"
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

    - name: Chart Setup
      run_once: true
      block:
        - name: Install chart
          kubernetes.core.helm:
            chart_ref: "{{ harbor_project_chart }}"
            chart_version: "{{ harbor_vars.kubernetes.helm.chart.version }}"
            create_namespace: true
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            name: "{{ harbor_vars.kubernetes.helm.chart.name }}"
            namespace: "{{ harbor_vars.kubernetes.namespace }}"
            update_repo_cache: true
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed
