---
- name: Reload SSH
  service:
    name: ssh
    state: reloaded

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted