---
kong_vars:
  log_level: info
  kubernetes:
    namespace: kong-system
    helm:
      repository:
        org: kong
        url: https://charts.konghq.com
        github: Kong/charts
    ingress_controller:
      helm:
        release:
          name: kong
        chart:
          name: ingress
          version: "{{ versions.kong_chart }}"
    custom_plugins:
      helm:
        chart:
          name: kong-plugins
          version: "{{ versions.kong_plugins_chart }}"
        repository:
          name: unique
          url: https://unique-ag.github.io/helm-charts/
    gateway:
      name: kong
  zitadel:
    domain: id.{{ domain }}
    project_id: "{{ zitadel.project_id }}"
  app:
    domain: app.{{ domain }}
