spec:
  name: document-chat-web-app-theme
  autoSync: false
  source:
    chart: web-app
    repoURL: harbor.konsti.org/library
    targetRevision: 0.10.0
    helm:
      releaseName: web-app-theme
      valuesObject:
        nameOverride: web-app-theme
        image:
          repository: harbor.konsti.org/library/web-app-theme
          tag: "2024.50"
        env:
          SELF_URL: https://app.konsti.org/theme
          THEME_BACKEND_API_URL: https://api.konsti.org/theme
          CHAT_BACKEND_API_URL: https://api.konsti.org/chat
          ZITADEL_ISSUER: https://id.konsti.org
          ZITADEL_CLIENT_ID: "286693043208258255"
          ZITADEL_PROJECT_ID: "null" # Not required any more, as Kong extracts roles from JWT
          CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.konsti.org; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.konsti.org wss://*.konsti.org; media-src 'self' *.konsti.org; frame-ancestors 'self'; frame-src 'self' *.konsti.org;"
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            memory: 350Mi
        livenessProbe:
          httpGet:
            path: /theme/api/health
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /theme/api/health
          initialDelaySeconds: 5
        httproute:
          enabled: true
          hostnames:
            - app.konsti.org
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /theme
