spec:
  name: document-chat-service-debug
  autoSync: true
  source:
    chart: backend-service
    repoURL: harbor.konsti.org/library
    targetRevision: 0.5.0
    helm:
      releaseName: service-debug
      valuesObject:
        nameOverride: service-debug
        image:
          repository: harbor.konsti.org/library/debug
          tag: 2024-09-12-56806
        service:
          port: 9494
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            memory: 350Mi
        livenessProbe:
          httpGet:
            path: /probe
        readinessProbe:
          httpGet:
            path: /probe
        httproute:
          enabled: true
          hostnames:
            - api.konsti.org
          annotations:
            konghq.com/strip-path: "true"
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /debug
                    