spec:
  name: document-chat-service-debug
  autoSync: false
  source:
    chart: backend-service
    repoURL: harbor.konsti.org/library
    targetRevision: 0.11.1
    helm:
      releaseName: service-debug
      valuesObject:
        nameOverride: service-debug
        image:
          repository: harbor.konsti.org/library/debug
          tag: 2024-09-12-56806
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            memory: 350Mi
        httproute:
          enabled: true
          hostnames:
            - api.konsti.org
          annotations:
            konghq.com/strip-path: "true"
            konghq.com/plugins: unique-jwt-auth
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /debug
