---
stackgres_vars:
  kubernetes:
    helm:
      chart:
        name: stackgres-operator
        version: "{{ versions.stackgres }}"
      repository:
        org: stackgres-charts
        url: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
        github: ongres/stackgres
    namespace: database
    adminui:
      service:
        type: ClusterIP
    grafana:
      autoEmbed: false
      webHost: monitoring-grafana.monitoring
      secretNamespace: monitoring
      secretName: monitoring-grafana
      secretUserKey: admin-user
      secretPasswordKey: admin-password
    ingress:
      subdomain: stackgres