---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - k3s

- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ external_secrets_vars.kubernetes.helm.repository.org }}"
        repo_url: "{{ external_secrets_vars.kubernetes.helm.repository.url }}"

    - name: Chart Setup
      kubernetes.core.helm:
        chart_ref: "{{ external_secrets_project_chart }}"
        chart_version: "{{ external_secrets_vars.kubernetes.helm.chart.version }}"
        create_namespace: true
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
        name: "{{ external_secrets_vars.kubernetes.helm.chart.name }}"
        namespace: "{{ external_secrets_vars.kubernetes.namespace }}"
        update_repo_cache: true
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed
