---
- name: Set operator project chart fact
  ansible.builtin.set_fact:
    rook_ceph_operator_project_chart: "{{ rook_ceph_vars.kubernetes.helm.repository.name }}/{{ rook_ceph_vars.kubernetes.helm.chart.operator.name }}"
  run_once: true

- name: Set cluster project chart fact
  ansible.builtin.set_fact:
    rook_ceph_cluster_project_chart: "{{ rook_ceph_vars.kubernetes.helm.repository.name }}/{{ rook_ceph_vars.kubernetes.helm.chart.cluster.name }}"
  run_once: true

- name: Set project url fact
  ansible.builtin.set_fact:
    rook_ceph_project_url: "{{ rook_ceph_vars.kubernetes.helm.repository.github }}/releases/tag"
  run_once: true

- name: Set project tag url fact
  ansible.builtin.set_fact:
    rook_ceph_project_url_tag: "{{ rook_ceph_project_url }}/{{ rook_ceph_vars.kubernetes.helm.chart.version }}"
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    rook_ceph_vars: "{{ rook_ceph_vars }}"
  run_once: true