---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - basic_auth
    - certmanager
    - k3s
    - helm

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ ray_vars.kubernetes.helm.repository.org }}"
        repo_url: "{{ ray_vars.kubernetes.helm.repository.url }}"

    - name: Chart Setup
      run_once: true
      block:
        - name: Install ray operator
          kubernetes.core.helm:
            chart_ref: "{{ ray_operator_project_chart }}"
            chart_version: "{{ ray_vars.kubernetes.helm.chart.version }}"
            create_namespace: true
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            name: "{{ ray_vars.kubernetes.operator.helm.chart.name }}"
            namespace: "{{ ray_vars.kubernetes.namespace }}"
            update_repo_cache: true
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Create huggingface secret
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'huggingface_secret.j2') | from_yaml }}"
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            wait: true
        
        - name: Create prometheus monitors
          block:
            - name: Create head monitor
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'head_monitor.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true

            - name: Create worker monitor
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'worker_monitor.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
                wait: true
        
        - name: Create Grafana dashboard ConfigMaps
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'dashboard.j2') | from_yaml }}"
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            wait: true
          loop:
            - data_grafana_dashboard.json
            - serve_grafana_dashboard.json
            - serve_deployment_grafana_dashboard.json
            - default_grafana_dashboard.json
          loop_control:
            loop_var: dashboard_file
          vars:
            dashboard_content: "{{ lookup('file', 'docs/grafana_dashboards/' + dashboard_file) | from_json | to_nice_json }}"
