apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-app.fullname" . }}
data:
  VERSION: {{ .Values.image.tag | quote }}
  PORT: {{ include "web-app.applicationPort" $ | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

