{{- if .Values.httproute.enabled -}}
{{- $fullName := include "web-app.fullname" . -}}
{{- $svcPort := include "web-app.servicePort" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.httproute.gatewayName }}
    namespace: {{ .Values.httproute.gatewayNamespace }}
    group: gateway.networking.k8s.io
    kind: Gateway
  hostnames:
  {{- range .Values.httproute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  {{- range .Values.httproute.rules }}
  - {{ toYaml (omit . "backendRefs" "skipBackendRefs") | nindent 4 }}
    {{- if not .skipBackendRefs }}
    backendRefs:
    {{- if .backendRefs }}
    {{- toYaml .backendRefs | nindent 4 }}
    {{- else }}
    - name: {{ $fullName }}
      port: {{ $svcPort }}
      kind: Service
    {{- end }}
    {{- end }}
  {{- end }}
---
{{- range .Values.httproute.additionalRoutes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}
  labels:
    {{- include "web-app.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ $.Values.httproute.gatewayName }}
    namespace: {{ $.Values.httproute.gatewayNamespace }}
    group: gateway.networking.k8s.io
    kind: Gateway
  hostnames:
  {{- range .hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  {{- toYaml .rules | nindent 2 }}
{{- end }}
{{- end }}