apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: postgres-object-storage-bucket
  namespace: document-chat
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  bucketName: postgres-backup
  storageClassName: ceph-bucket