apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  namespace: document-chat
  name: postgres-pooling-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        pool_mode: transaction
        max_client_conn: '1000'
        default_pool_size: '80'