---
longhorn_vars:
  kubernetes:
    default_settings:
      backup:
        enabled: false
        secret:
          name: longhorn-secret
        target: <target>
        user:
          name: <user>
          password: <password>
      data_locality: strict-local
      orphan_auto_deletion: true
      pod_deletion_policy: delete-both-statefulset-and-deployment-pod
      replica_auto_balance: best-effort
      replicas: 3
    helm:
      chart:
        name: longhorn
        version: "{{ versions.longhorn }}"
      repository:
        name: longhorn
        org: longhorn
        url: https://charts.longhorn.io
    ingress:
      subdomain: longhorn
    namespace: kube-system
    persistence:
      data_locality: best-effort
      migratable: true
      replicas: 3
