---
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_check

- name: Reboot the server if required
  reboot:
    reboot_timeout: 5
    connect_timeout: 5
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  become: true
  ignore_errors: true
  when: reboot_required_check.stat.exists

- name: Update Ansible user after reboot
  set_fact:
    ansible_user: "{{ cluster_vars.management_user }}"
  when: reboot_required_check.stat.exists

- name: Ensure connection with new management user
  wait_for_connection:
    delay: 10
    timeout: 300
  when: reboot_required_check.stat.exists
