apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-bedrock-claude-sonnet-ingress
  namespace: document-chat
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - claude.konsti.org
      secretName: aws-bedrock-claude-sonnet-tls
  rules:
    - host: claude.konsti.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aws-bedrock-claude-sonnet
                port:
                  number: 80
