---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - k3s

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Get secret definitions
      set_fact:
        secret_definitions: "{{ secret_definitions | default([]) + [lookup('ansible.builtin.template', item + '.secrets.j2', errors='ignore') | from_yaml] }}"
      loop: "{{ apps }}"
      loop_control:
        loop_var: item

    - name: Create namespaces if they don't exist
      kubernetes.core.k8s:
        name: "{{ item.spec.destination.namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
      loop: "{{ secret_definitions | selectattr('spec.destination.namespace', 'defined') | list }}"

    - name: Create ArgoCD Applications
      kubernetes.core.k8s:
        definition: "{{ lookup('ansible.builtin.template', item + '.argo-app.j2') | from_yaml }}"
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
        wait: true
      loop: "{{ apps }}"
      loop_control:
        loop_var: item

    - name: Create Secrets for Apps
      kubernetes.core.k8s:
        definition: "{{ lookup('ansible.builtin.template', item + '.secrets.j2', errors='ignore') | from_yaml }}"
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
        wait: true
      loop: "{{ apps }}"
      loop_control:
        loop_var: item
      when: lookup('ansible.builtin.template', item + '.secrets.j2', errors='ignore') != ''
