---
loki_vars:
  kubernetes:
    namespace: monitoring
    helm:
      chart:
        name: loki
        version: "{{ versions.loki }}"
      repository:
        org: grafana
        name: helm-charts
        url: https://grafana.github.io
  alloy:
    helm:
      chart:
        name: alloy
        version: "{{ versions.alloy }}"
  promtail:
    helm:
      chart:
        name: promtail
        version: "{{ versions.promtail }}"