---
loki_vars:
  kubernetes:
    namespace: monitoring
    helm:
      chart:
        name: loki
        version: 6.12.0
      repository:
        org: grafana
        name: helm-charts
        url: https://grafana.github.io
