---
zitadel_vars:
  image:
    tag: "{{ versions.zitadel }}"
  kubernetes:
    namespace: zitadel
    helm:
      chart:
        name: zitadel
        version: "{{ versions.zitadel_helm_chart }}"
      repository:
        org: zitadel
        url: https://charts.zitadel.com
        github: zitadel/zitadel-charts
    ingress:
      subdomain: id
  postgres_cluster:
    name: zitadel-db-cluster
    user: zitadel
    database: zitadel
        
