apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm.fullname" . }}-environment
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "3"
data:
  HOST: "{{ .Values.listen | default "0.0.0.0" }}"
  PORT: {{ .Values.service.port | quote}}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
