---
tailscale_vars:
  kubernetes:
    namespace: tailscale
    helm:
      chart:
        name: tailscale-operator
        version: "{{ versions.tailscale }}"
      repository:
        org: tailscale
        url: https://pkgs.tailscale.com/helmcharts
