---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Role Post-Install
  notify: Restart service
  when:
    - k3s_ha_cluster
    - ansible_host in k3s_server_hosts
  block:
    - name: Set server configuration postinstall fact
      ansible.builtin.set_fact:
        k3s_config_postinstall: true

    - name: Update server configuration file
      ansible.builtin.template:
        src: config.j2
        dest: '{{ k3s_vars.directory.config }}/config.yaml'
        owner: root
        group: root
        mode: '0600'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers