---
- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Role Validation
  run_once: true
  block:
    - name: Validate inventory
      ansible.builtin.assert:
        that: k3s_ha_cluster or k3s_non_ha_cluster
        fail_msg: |-
          ERROR: Invalid number of 'server' type nodes.
            - Defined nodes: {{ k3s_server_hosts | length }} ({{ k3s_server_hosts | join(', ') }})
            - Valid values: 1, higher than 2
          FIXES:
            - Update the number of 'server' type nodes, into inventory file.
        quiet: true
