spec:
  name: document-chat-web-app-chat
  autoSync: true
  source:
    chart: web-app
    repoURL: harbor.konsti.org/library
    targetRevision: 0.8.0
    helm:
      releaseName: web-app-chat
      valuesObject:
        nameOverride: web-app-chat
        image:
          repository: harbor.konsti.org/library/web-app-chat
          tag: 2024.38
        service:
          port: 3000
        env:
          SELF_URL: https://app.konsti.org/chat
          KNOWLEDGE_UPLOAD_APP_URL: https://app.konsti.org/knowledge-upload
          CHAT_APP_URL: https://app.konsti.org/chat
          ADMIN_APP_URL: https://app.konsti.org/admin
          INGESTION_BACKEND_API_URL: https://api.konsti.org/ingestion
          THEME_BACKEND_API_URL: https://api.konsti.org/theme
          CHAT_BACKEND_API_URL: https://api.konsti.org/chat
          ZITADEL_ISSUER: https://id.konsti.org
          ZITADEL_CLIENT_ID: "286693043208258255"
          ZITADEL_PROJECT_ID: "null" # Not required any more, as Kong extracts roles from JWT
          CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.konsti.org; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.konsti.org wss://*.konsti.org; media-src 'self' *.konsti.org; frame-ancestors 'self'; frame-src 'self' *.konsti.org;"
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            memory: 350Mi
        livenessProbe:
          httpGet:
            path: /chat/api/health
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /chat/api/health
          initialDelaySeconds: 5
        httproute:
          enabled: true
          hostnames:
            - app.konsti.org
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /chat
          additionalRoutes:
            - name: web-app-root
              hostnames:
                - app.konsti.org
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  filters:
                    - type: RequestRedirect
                      requestRedirect:
                        scheme: https
                        hostname: app.konsti.org
                        path:
                          type: ReplaceFullPath
                          replaceFullPath: /chat
                        statusCode: 302 # Temporary Redirect, as we might change the root path in the future
                        port: 443

