{{- $fullName := include "litellm.fullname" . -}}
{{- if .Values.hooks.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-db-migration
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
    app.kubernetes.io/component: hooks-db-migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 2
  template:
    metadata:
      name: {{ $fullName }}-db-migration
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "litellm.labels" . | nindent 8 }}
        app.kubernetes.io/component: hooks-db-migration
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.hooks.migration.initContainers }}
      initContainers:
      {{- range .Values.hooks.migration.initContainers }}
        - name: {{ .name | default (printf "init-%s" $fullName) }}
          image: "{{ .image | default "busybox:1.28" }}"
          restartPolicy: "{{ .restartPolicy | default "Always" }}"
          command: {{ .command | toYaml | nindent 10 }}
          {{- if .volumeMounts }}
          volumeMounts:
          {{- range .volumeMounts }}
            - name: {{ .name}}
              mountPath: {{ .mountPath}}   
          {{- end }}
          {{- end }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ default "db-migration" .Values.hooks.migration.name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "main-%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - {{ .Values.hooks.migration.command | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: DISABLE_SCHEMA_UPDATE
              value: "false" #  always run the migration from the Helm PreSync hook, override the value set
          envFrom:
            - configMapRef:
                name: {{ $fullName }}-environment
            {{- if .Values.secretFrom }}
            - secretRef:
                name: {{ .Values.secretFrom.name }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
