---
argocd_vars:
  kubernetes:
    application_set:
      replicas: 2
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
    configs:
      cm:
        exec:
          enabled: true
      params:
        server:
          insecure: true
    controller:
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
    dex:
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
    helm:
      chart:
        name: argo-cd
        org: argoproj
        version: "{{ versions.argocd }}"
      repository:
        name: argo-helm
        org: argoproj
        url: https://argoproj.github.io
    namespace: argocd
    notifications:
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
    redis:
      high_availability:
        enabled: false
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
    repo_server:
      autoscaling:
        enabled: false
        min_replicas: 2
        target:
          cpu_percentage: 60
          memory_percentage: 80
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
    server:
      admin:
        password: "{{ argocd.server.admin.password }}"
      application:
        namespaces:
          - argocd
      autoscaling:
        enabled: true
        min_replicas: 2
        target:
          cpu_percentage: 60
          memory_percentage: 80
      ingress:
        subdomain: argocd
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
      user:
        name: user
        password: "{{ argocd.server.user.password }}"
