spec:
  name: document-chat-web-app-admin
  autoSync: true
  source:
    chart: web-app
    repoURL: harbor.konsti.org/library
    targetRevision: 0.8.0
    helm:
      releaseName: web-app-admin
      valuesObject:
        nameOverride: web-app-admin
        image:
          repository: harbor.konsti.org/library/web-app-admin
          tag: 2024.50
        service:
          port: 3000
        env:
          SELF_URL: https://app.konsti.org/admin
          KNOWLEDGE_UPLOAD_APP_URL: https://app.konsti.org/knowledge-upload
          CHAT_APP_URL: https://app.konsti.org/chat
          INGESTION_BACKEND_API_URL: https://api.konsti.org/ingestion
          THEME_BACKEND_API_URL: https://api.konsti.org/theme
          CHAT_BACKEND_API_URL: https://api.konsti.org/chat
          SCOPE_MANAGEMENT_BACKEND_API_URL: https://api.konsti.org/scope-management
          APP_REPOSITORY_BACKEND_API_URL: https://api.konsti.org/apps
          ZITADEL_ISSUER: https://id.konsti.org
          ZITADEL_CLIENT_ID: "286693043208258255"
          ZITADEL_PROJECT_ID: "null" # Not required any more, as Kong extracts roles from JWT
          FEATURE_FLAG_NEW_TRANSLATION_UI_UN_7233: "true"
          CONTENT_SECURITY_POLICY_VALUE: "default-src 'self'; img-src https: blob: data: *.konsti.org; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' blob: *.konsti.org wss://*.konsti.org; media-src 'self' *.konsti.org; frame-ancestors 'self'; frame-src 'self' *.konsti.org;"
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            memory: 350Mi
        livenessProbe:
          httpGet:
            path: /admin/api/health
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /admin/api/health
          initialDelaySeconds: 5
        httproute:
          enabled: true
          hostnames:
            - app.konsti.org
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /admin
