---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - k3s
    - certmanager
    - basic_auth

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ prometheus_vars.kubernetes.helm.repository.org }}"
        repo_url: "{{ prometheus_vars.kubernetes.helm.repository.url }}/{{ prometheus_vars.kubernetes.helm.repository.name }}"

    - name: Chart Setup
      run_once: true
      block:
        - name: Create the prometheus namespace
          kubernetes.core.k8s:
            name: "{{ prometheus_vars.kubernetes.namespace }}"
            api_version: v1
            kind: Namespace
            state: present
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            wait: true

        - name: Create grafana secret
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'grafana_secret.j2') | from_yaml }}"
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            wait: true

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: "{{ prometheus_project_chart }}"
            chart_version: "{{ prometheus_vars.kubernetes.helm.chart.version }}"
            create_namespace: true
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            name: "{{ prometheus_vars.kubernetes.helm.chart.prefix }}"
            namespace: "{{ prometheus_vars.kubernetes.namespace }}"
            update_repo_cache: true
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed
