---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - k3s

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ stackgres_vars.kubernetes.helm.repository.org }}"
        repo_url: "{{ stackgres_vars.kubernetes.helm.repository.url }}"
        
    - name: Chart Setup
      run_once: true
      block:
        - name: Install chart
          kubernetes.core.helm:
            chart_ref: "{{ stackgres_project_chart }}"
            chart_version: "{{ stackgres_vars.kubernetes.helm.chart.version }}"
            create_namespace: true
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            name: "{{ stackgres_vars.kubernetes.helm.chart.name }}"
            namespace: "{{ stackgres_vars.kubernetes.namespace }}"
            update_repo_cache: true
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Create ingress
          kubernetes.core.k8s:
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            definition: "{{ lookup('ansible.builtin.template', 'ingress.j2') }}"
            namespace: "{{ stackgres_vars.kubernetes.namespace }}"