---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - k3s

- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ tailscale_vars.kubernetes.helm.repository.org }}"
        repo_url: "{{ tailscale_vars.kubernetes.helm.repository.url }}"

    - name: Create namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ tailscale_vars.kubernetes.namespace }}"
        wait: true

    - name: Create oauth secret
      kubernetes.core.k8s:
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: operator-oauth
            namespace: "{{ tailscale_vars.kubernetes.namespace }}"
          stringData:
            client_id: "{{ tailscale.oauth_client_id }}"
            client_secret: "{{ tailscale.oauth_client_secret }}"
        wait: true

    - name: Chart Setup
      kubernetes.core.helm:
        chart_ref: "{{ tailscale_project_chart }}"
        chart_version: "{{ tailscale_vars.kubernetes.helm.chart.version }}"
        create_namespace: true
        force: true
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
        name: "{{ tailscale_vars.kubernetes.helm.chart.name }}"
        namespace: "{{ tailscale_vars.kubernetes.namespace }}"
        update_repo_cache: true
        values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed
        