---
harbor_vars:
  kubernetes:
    helm:
      chart:
        name: harbor
        version: "{{ versions.harbor }}"
      repository:
        name: harbor
        org: harbor
        url: https://helm.goharbor.io
        github: goharbor/harbor-helm
    namespace: harbor
  admin:
    password: "{{ harbor.admin.password }}"
  ingress:
    hostname: harbor.{{ cluster.domain }}
  persistence:
    storage_class: ceph-block
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  postgres:
    user: harbor
    password: "{{ harbor.postgres.password }}"
    coreDatabase: registry 