- name: Set zitadel project chart fact
  ansible.builtin.set_fact:
    zitadel_project_chart: '{{ zitadel_vars.kubernetes.helm.repository.org }}/{{ zitadel_vars.kubernetes.helm.chart.name }}'
  run_once: true

- name: Set project url fact
  ansible.builtin.set_fact:
    zitadel_project_url: https://github.com/{{ zitadel_vars.kubernetes.helm.repository.github }}
  run_once: true

- name: Set project tag url fact
  ansible.builtin.set_fact:
    zitadel_project_url_tag: '{{ zitadel_project_url }}/releases/tag/{{ zitadel_vars.kubernetes.helm.chart.name }}-{{ zitadel_vars.kubernetes.helm.chart.version }}'
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    zitadel_vars: '{{ zitadel_vars }}'
  run_once: true
