---
- name: Set project chart fact
  ansible.builtin.set_fact:
    argocd_project_chart: '{{ argocd_vars.kubernetes.helm.chart.org }}/{{ argocd_vars.kubernetes.helm.chart.name }}'
  run_once: true

- name: Set project release fact
  ansible.builtin.set_fact:
    argocd_project_release: '{{ argocd_vars.kubernetes.helm.repository.org }}/{{ argocd_vars.kubernetes.helm.repository.name }}'
  run_once: true

- name: Set project url fact
  ansible.builtin.set_fact:
    argocd_project_url: https://github.com/{{ argocd_project_release }}/releases/tag
  run_once: true

- name: Set project tag url fact
  ansible.builtin.set_fact:
    argocd_project_url_tag: '{{ argocd_project_url }}/{{ argocd_vars.kubernetes.helm.chart.name }}-{{ argocd_vars.kubernetes.helm.chart.version[1:] }}'
  run_once: true
