---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Role Reset
  when: ansible_host in k3s_server_hosts
  block:
    - name: Remove repository
      kubernetes.core.helm_repository:
        name: "{{ nvidia_gpu_operator_vars.kubernetes.helm.repository.org }}"
        repo_state: absent

    - name: Uninstall NVIDIA GPU Operator
      kubernetes.core.helm:
        name: "{{ nvidia_gpu_operator_vars.kubernetes.helm.chart.name }}"
        namespace: "{{ nvidia_gpu_operator_vars.kubernetes.namespace }}"
        kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
        state: absent