apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-service.fullname" . }}
data:
  VERSION: {{ .Values.image.tag | quote }}
  PORT: {{ .Values.service.port | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
