apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-service.fullname" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "3"
data:
  VERSION: {{ .Values.image.tag | quote }}
  PORT: {{ include "backend-service.applicationPort" $ | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
