{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "backend-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "2"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "backend-service.fullname" . }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy | default "Owner" }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy | default "Retain" }}
    template:
      engineVersion: v2
      data:
        {{- range $key, $value := .Values.externalSecret.target.template.data }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}