{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-service.fullname" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "backend-service.servicePort" . }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend-service.selectorLabels" . | nindent 4 }}
{{- end }}